In [5]:
import numpy as np


In [3]:
x = np.array([1,3,5,4,2,8])
print(x)
print(type(x))
print(x.ndim)

[1 3 5 4 2 8]
<class 'numpy.ndarray'>
1


In [13]:
y = [1,23,4,5]
print(y)
print(type(y))

[1, 23, 4, 5]
<class 'list'>


In [15]:
%timeit [j**4 for j in range(1,9)]

1.87 μs ± 210 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
%timeit np.arange(1,9)**4

5.01 μs ± 563 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [27]:
x = [1,2,3,4,5,6]
y = np.array(x)
print(y)
y

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [38]:
l = []
for i in range(1,6):
    num = int(input("Enter Numebr: "))
    l.append(num)
print(np.array(l))

Enter Numebr:  3
Enter Numebr:  4
Enter Numebr:  5
Enter Numebr:  6
Enter Numebr:  7


[3 4 5 6 7]


In [46]:
x1 = np.array([[[1,2,3,4]]])
print(x1)
print(x1.ndim)

[[[1 2 3 4]]]
3


# 2D Array

In [56]:
array2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array2D)
print(array2D.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


# 3D Array

In [59]:
array3D = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(array3D)
print(array3D.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [69]:
arn = np.array([1,2,3,4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Zero

In [92]:
arr_zero = np.zeros(4)
print(arr_zero)

print()

arr_zero1 = np.zeros((4,5))
print(arr_zero1)
print(arr_zero1.ndim)

[0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2


# One

In [15]:
arr_one = np.ones(6)
print(arr_one)

print()

arr_one1 = np.ones((6,6))
print(arr_one1)
print(arr_one1.ndim)

[1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
2


# Empty Array

In [17]:
arr_empty = np.empty(4)
print(arr_empty)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 2.37666896e-312]


# Range Array

In [123]:
arr_range = np.arange(6)
print(arr_range)

print()

arr_range1 = np.arange(2,9)
print(arr_range1)

[0 1 2 3 4 5]

[2 3 4 5 6 7 8]


# Diagonal

In [128]:
ar_dia = np.eye(3)
print(ar_dia)
print(ar_dia.ndim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2


In [130]:
ar_dia1 = np.eye(4,6)
print(ar_dia1)
print(ar_dia1.ndim)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
2


# Linespace

In [147]:
arr_lin = np.linspace(0,20,num=5)
print(arr_lin)

[ 0.  5. 10. 15. 20.]


In [151]:
arr_lin1 = np.linspace(0,10,num=5)
print(arr_lin1)

[ 0.   2.5  5.   7.5 10. ]


# Random Function

## rand()

In [157]:
arr_rand = np.random.rand(4)
print(arr_rand)

[0.79642312 0.41487399 0.73496172 0.3083368 ]


In [163]:
arr_rand1 = np.random.rand(2,5)
print(arr_rand1)

[[0.59693211 0.0466201  0.87445692 0.19445679 0.66840615]
 [0.86271861 0.34805487 0.74223423 0.66798497 0.36671436]]


## randn()

In [175]:
arr_randn = np.random.randn(5)
print(arr_randn)

[-0.27600066  0.47648089  0.24415637 -0.75674389 -0.87611168]


## ranf()

In [178]:
arr_ranf = np.random.ranf(4)
print(arr_ranf)

[0.13067184 0.87402214 0.72089358 0.22379299]


## randint(min, max, total_value)

In [185]:
arr_randint = np.random.randint(5,20,5)
print(arr_randint)

[18 19 14  6  6]


# DATA TYPE

In [7]:
var = np.array([1,2,3,4,5])
print("Data Type: ", var.dtype)

Data Type:  int64


In [25]:
var = np.array([1.0, 2.3, 3.0, 4.0, 5.0])
print("Data Type: ", var.dtype)

Data Type:  float64


In [27]:
var = np.array(["A", "C", "D"])
print("Data Type: ", var.dtype)

Data Type:  <U1


In [75]:
var = np.array([1,2,3,4,5,0,-7], dtype = np.complex_)
print(var)
print("Data Type: ", var.dtype)

[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  0.+0.j -7.+0.j]
Data Type:  complex128


# Shape

In [9]:
arr = np.array([[1,2],[1,2]])
print(arr)
print()

print(arr.shape)

[[1 2]
 [1 2]]

(2, 2)


In [11]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print()

print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]

(2, 4)


n Dimension array

In [16]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print(arr.ndim)
print()

print(arr.shape)

[[[[[1 2 3 4]]]]]
5

(1, 1, 1, 1, 4)


# Reshape

In [23]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))
print()

arr1 = np.array([1,2,3,4,5,6,7,8])
print(arr1.reshape(4,2))

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Arithematic Operation

## Addition (+)

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
sum = arr + 3
print(sum)

[4 5 6 7]


In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
sum = arr1 + arr2
print(sum)

[2 4 6 8]


### or

In [18]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
sum = np.add(arr1,arr2)
print(sum)

[2 4 6 8]


### Add 2D Array

In [10]:
arr1 = np.array([[1,2,3,4],[1,2,3,4]])
arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr1)
print(arr2)
print()
sum = np.add(arr1,arr2)
print(sum)

[[1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


## Subtraction (-)

In [2]:
arr = np.array([1,2,3,4])
sub = arr - 2
print(sub)

[-1  0  1  2]


In [6]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
sub = arr1 - arr2
print(sub)
print()
sub2 = np.subtract(arr1,arr2)
print(sub2)

[0 0 0 0]

[0 0 0 0]


## Multiplication (*)

In [7]:
arr = np.array([1,2,3,4])
multi = arr * 2
print(multi)

[2 4 6 8]


In [11]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
multi = arr1 * arr2
print(multi)

[ 5 12 21 32]


### Multiply 2D Array

In [12]:
arr1 = np.array([[1,2,3,4],[1,2,3,4]])
arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr1)
print(arr2)
print()
mul = np.multiply(arr1,arr2)
print(mul)

[[1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]


## Division (/)

In [13]:
arr = np.array([1,2,3,4])
div = arr / 2
print(div)

[0.5 1.  1.5 2. ]


In [15]:
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,2,3,4])
div = arr1 /arr2
print(div)

[2. 2. 2. 2.]


## Modulus

In [17]:
arr1 = np.array([3,4,5,10])
arr2 = np.array([1,2,3,4])
mod = arr1 % arr2
print(mod)

[0 0 2 2]


# Arithmetic Funtion

In [45]:
arr = np.array([1,2,3,4,5,0,7,3,1])
print("Minimun Value: ",np.min(arr), np.argmin(arr))
print("Maximun Value: ",np.max(arr), np.argmax(arr))
print("Sqrt Value: ",np.sqrt(arr))

arr11 = np.array([1,2,3,4])
print("cumsum Value: ",np.cumsum(arr11))
print("sin Value: ",np.sin(arr11))
print("cos Value: ",np.cos(arr11))

Minimun Value:  0 5
Maximun Value:  7 6
Sqrt Value:  [1.         1.41421356 1.73205081 2.         2.23606798 0.
 2.64575131 1.73205081 1.        ]
cumsum Value:  [ 1  3  6 10]
sin Value:  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
cos Value:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [29]:
arr1 = np.array([[4,25,36,14],[11,92,3,40]])
print(arr1)
print()
print(np.min(arr1, axis=0))
print(np.min(arr1, axis=1))

[[ 4 25 36 14]
 [11 92  3 40]]

[ 4 25  3 14]
[4 3]


In [65]:
arr1 = np.array([[[4,25,36,14],[56,60,23,100],[11,92,3,40]]])
print(arr1,"\n", arr1.ndim)
print()
print(np.min(arr1, axis=0))   # axix = 0 (Row)
print()
print(np.min(arr1, axis=1))   # axix = 1 (Column)

[[[  4  25  36  14]
  [ 56  60  23 100]
  [ 11  92   3  40]]] 
 3

[[  4  25  36  14]
 [ 56  60  23 100]
 [ 11  92   3  40]]

[[ 4 25  3 14]]


# Broadcasting in Numpy

In [60]:
arr1 = np.array([1,2,3])
print(arr1)
print(arr1.shape)
print()

arr2 = np.array([[1],[2],[3]])
print(arr2)
print(arr2.shape)
print()
print(arr1 + arr2)

[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [61]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(arr1.shape)
print()

arr2 = np.array([[1],[2],[3]])
print(arr2)
print(arr2.shape)
print()

print(arr1 + arr2)

[1 2 3 4 5 6]
(6,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4 5 6 7]
 [3 4 5 6 7 8]
 [4 5 6 7 8 9]]


In [67]:
arr1 = np.array([1,2,3])
print(arr1)
print(arr1.shape)
print()

arr2 = np.array([[1],[2],[3],[4]])
print(arr2)
print(arr2.shape)
print()

print(arr1 + arr2)

[1 2 3]
(3,)

[[1]
 [2]
 [3]
 [4]]
(4, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


# Indexing Numpy Array

#### 1-D Array

In [7]:
arr = np.array([8,4,0,2,6])
#               0 1 2 3 4 
#              -5-4-3-2-1

print(arr[3])
print(arr[-2])

2
2


#### 2-D Array

In [17]:
arr1 = np.array([[2,3,5],[9,4,8]])
print(arr1)
print(arr1.ndim)
print(arr1[1,2])

[[2 3 5]
 [9 4 8]]
2
8


#### 3-D Array

In [26]:
arr2 = np.array([[[1,3,2],[4,7,0],[9,6,8]]])
print(arr2)
print(arr2.ndim)
print(arr2[0,2,1])

[[[1 3 2]
  [4 7 0]
  [9 6 8]]]
3
6


# Slicing Numpy Array

#### 1-D Array

In [48]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr)
print()
print("3 to 8: ", arr[2:8])
print("2 to End: ", arr[1:])
print("Start to 7:", arr[:7])
print("Stop: ", arr[::2])
print("Stop: ", arr[2:8:2])

[1 2 3 4 5 6 7 8 9 0]

3 to 8:  [3 4 5 6 7 8]
2 to End:  [2 3 4 5 6 7 8 9 0]
Start to 7: [1 2 3 4 5 6 7]
Stop:  [1 3 5 7 9]
Stop:  [3 5 7]


#### 2-D Array

In [68]:
arr1 = np.array([[23,55,78,44,36],[77,10,90,50,20]])
print(arr1)
print()
print(arr1[0,3:])
print(arr1[1,2:])
print(arr1[1,1:5])

[[23 55 78 44 36]
 [77 10 90 50 20]]

[44 36]
[90 50 20]
[10 90 50 20]


# Iterating Numpay Array

### For-Loop

In [87]:
arr = np.array([4,6,8,0,1,3,5,7,1])
print(arr)
print()

for i in arr:
    print(i)

[4 6 8 0 1 3 5 7 1]

4
6
8
0
1
3
5
7
1


In [93]:
arr1 = np.array([[1,2,3,4],[6,7,8,9]])
print(arr1)
print()

for i in arr1:
    print(i)

print()

for j in arr1:
    for k in j:
        print(k)

[[1 2 3 4]
 [6 7 8 9]]

[1 2 3 4]
[6 7 8 9]

1
2
3
4
6
7
8
9


In [99]:
arr2 = np.array([[[1,2,3,4],[6,7,8,9]]])
print(arr2)
print(arr2.ndim)
print()

for i in arr2:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [6 7 8 9]]]
3

1
2
3
4
6
7
8
9


### np.nditer() it used for instead of for-loop

In [103]:
arr3 = np.array([[[1,2,3,4],[6,7,8,9]]])

for i in np.nditer(arr3):
    print()

1
2
3
4
6
7
8
9


In [113]:
arr3 = np.array([[[1,2,3,4],[6,7,8,9]]])

for i in np.nditer(arr3, flags=['buffered'],op_dtypes=["S"]):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'6'
b'7'
b'8'
b'9'


### np.ndenumerate()

In [117]:
arr3 = np.array([[[1,2,3,4],[6,7,8,9]]])

for i,d in np.ndenumerate(arr3):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
